--------------------------------------------------------
--  File created - Tuesday-October-10-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PREDMET
--------------------------------------------------------

  CREATE TABLE "FAKULTET"."PREDMET" 
   (	"PREDMET_ID" NUMBER(10,0), 
	"PREDMET" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FAKULTET.PREDMET
SET DEFINE OFF;
Insert into FAKULTET.PREDMET (PREDMET_ID,PREDMET) values (101,'matematika');
Insert into FAKULTET.PREDMET (PREDMET_ID,PREDMET) values (102,'fizika');
Insert into FAKULTET.PREDMET (PREDMET_ID,PREDMET) values (103,'engleski');
Insert into FAKULTET.PREDMET (PREDMET_ID,PREDMET) values (104,'srpski');
--------------------------------------------------------
--  DDL for Index PREDMET
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAKULTET"."PREDMET" ON "FAKULTET"."PREDMET" ("PREDMET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PREDMET
--------------------------------------------------------

  ALTER TABLE "FAKULTET"."PREDMET" ADD CONSTRAINT "PREDMET_PK" PRIMARY KEY ("PREDMET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FAKULTET"."PREDMET" MODIFY ("PREDMET" NOT NULL ENABLE);
  ALTER TABLE "FAKULTET"."PREDMET" MODIFY ("PREDMET_ID" NOT NULL ENABLE);
