--------------------------------------------------------
--  File created - Tuesday-October-10-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "FAKULTET"."STUDENT" 
   (	"STUDENT_ID" NUMBER(10,0), 
	"CODE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"SURNAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" NUMBER(10,0) DEFAULT 1, 
	"LAST_UPDATED_BY" NUMBER(10,0), 
	"LAST_UPDATED_DATE" DATE, 
	"ROW_STATUS" VARCHAR2(1 BYTE) DEFAULT 'A'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FAKULTET.STUDENT
SET DEFINE OFF;
Insert into FAKULTET.STUDENT (STUDENT_ID,CODE,NAME,SURNAME,DESCRIPTION,CREATION_DATE,CREATED_BY,LAST_UPDATED_BY,LAST_UPDATED_DATE,ROW_STATUS) values (1,'1','Marko','Markovic','Test',to_date('06-OCT-17','DD-MON-RR'),1,2,to_date('02-OCT-17','DD-MON-RR'),'A');
Insert into FAKULTET.STUDENT (STUDENT_ID,CODE,NAME,SURNAME,DESCRIPTION,CREATION_DATE,CREATED_BY,LAST_UPDATED_BY,LAST_UPDATED_DATE,ROW_STATUS) values (4,'1','Mirko','Alvirovic','Test',to_date('06-OCT-17','DD-MON-RR'),1,1,to_date('06-OCT-17','DD-MON-RR'),'A');
Insert into FAKULTET.STUDENT (STUDENT_ID,CODE,NAME,SURNAME,DESCRIPTION,CREATION_DATE,CREATED_BY,LAST_UPDATED_BY,LAST_UPDATED_DATE,ROW_STATUS) values (2,'1','Nikola','Ostojic','Test',to_date('02-OCT-17','DD-MON-RR'),1,2,to_date('02-OCT-17','DD-MON-RR'),'A');
Insert into FAKULTET.STUDENT (STUDENT_ID,CODE,NAME,SURNAME,DESCRIPTION,CREATION_DATE,CREATED_BY,LAST_UPDATED_BY,LAST_UPDATED_DATE,ROW_STATUS) values (5,'1','Marija','Vidosavljevic','Test',to_date('07-OCT-17','DD-MON-RR'),1,1,to_date('07-OCT-17','DD-MON-RR'),'A');
--------------------------------------------------------
--  DDL for Index STUDENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAKULTET"."STUDENT" ON "FAKULTET"."STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "FAKULTET"."STUDENT" MODIFY ("LAST_UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "FAKULTET"."STUDENT" MODIFY ("LAST_UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "FAKULTET"."STUDENT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FAKULTET"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FAKULTET"."STUDENT" MODIFY ("ROW_STATUS" NOT NULL ENABLE);
  ALTER TABLE "FAKULTET"."STUDENT" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "FAKULTET"."STUDENT" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "FAKULTET"."STUDENT" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "FAKULTET"."STUDENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "FAKULTET"."STUDENT" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "FAKULTET"."STUDENT" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
